const dummyJobs = [
  {
    _id: "1",
    title: "Senior Python Instructor",
    category: "teaching",
    type: "Full-time",
    location: "Bangalore, Karnataka",
    experience: "3-5 years",
    salary: "₹6-8 LPA",
    description: "Teach advanced Python programming, data structures, and algorithms to students. Develop curriculum and mentor students in real-world projects. Experience with Django/Flask frameworks preferred.",
    posted: "2024-01-15T10:30:00.000Z",
    urgent: true,
    featured: true
  },
  {
    _id: "2",
    title: "Full Stack Developer",
    category: "tech",
    type: "Full-time",
    location: "Remote",
    experience: "2-4 years",
    salary: "₹8-12 LPA",
    description: "Build and maintain web applications using React, Node.js, and MongoDB. Collaborate with the product team to implement new features and optimize performance.",
    posted: "2024-01-14T14:20:00.000Z",
    urgent: false,
    featured: true
  },
  {
    _id: "3",
    title: "Robotics & AI Trainer",
    category: "teaching",
    type: "Part-time",
    location: "Hyderabad, Telangana",
    experience: "1-3 years",
    salary: "₹4-6 LPA",
    description: "Teach robotics fundamentals, Arduino programming, and AI concepts to school students. Hands-on experience with robotics kits and programming required.",
    posted: "2024-01-13T09:15:00.000Z",
    urgent: false,
    featured: false
  },
  {
    _id: "4",
    title: "Operations Manager",
    category: "operations",
    type: "Full-time",
    location: "Delhi, NCR",
    experience: "4-6 years",
    salary: "₹10-15 LPA",
    description: "Oversee daily operations, manage center coordinators, and ensure smooth execution of educational programs. Strong organizational and leadership skills required.",
    posted: "2024-01-12T16:45:00.000Z",
    urgent: true,
    featured: false
  },
  {
    _id: "5",
    title: "Digital Marketing Specialist",
    category: "marketing",
    type: "Full-time",
    location: "Mumbai, Maharashtra",
    experience: "2-3 years",
    salary: "₹5-7 LPA",
    description: "Develop and execute digital marketing campaigns, manage social media channels, and analyze campaign performance. Experience with SEO/SEM and Google Analytics.",
    posted: "2024-01-11T11:20:00.000Z",
    urgent: false,
    featured: true
  },
  {
    _id: "6",
    title: "Mobile App Developer (Flutter)",
    category: "tech",
    type: "Contract",
    location: "Remote",
    experience: "1-2 years",
    salary: "₹3-5 LPA",
    description: "Develop cross-platform mobile applications using Flutter. Work on educational apps with features like video streaming, quizzes, and progress tracking.",
    posted: "2024-01-10T13:10:00.000Z",
    urgent: false,
    featured: false
  },
  {
    _id: "7",
    title: "Admissions Counselor",
    category: "sales",
    type: "Full-time",
    location: "Chennai, Tamil Nadu",
    experience: "1-2 years",
    salary: "₹4-6 LPA + Incentives",
    description: "Guide prospective students through admission process, conduct counseling sessions, and achieve enrollment targets. Excellent communication skills required.",
    posted: "2024-01-09T15:30:00.000Z",
    urgent: true,
    featured: false
  },
  {
    _id: "8",
    title: "Web Development Instructor",
    category: "teaching",
    type: "Part-time",
    location: "Pune, Maharashtra",
    experience: "2-3 years",
    salary: "₹5-7 LPA",
    description: "Teach HTML, CSS, JavaScript, and React to beginners. Create engaging projects and help students build portfolio websites. Teaching experience preferred.",
    posted: "2024-01-08T10:00:00.000Z",
    urgent: false,
    featured: false
  },
  {
    _id: "9",
    title: "Content Marketing Manager",
    category: "marketing",
    type: "Full-time",
    location: "Remote",
    experience: "3-5 years",
    salary: "₹7-9 LPA",
    description: "Develop content strategy, create educational blog posts, manage email campaigns, and collaborate with instructors for course content creation.",
    posted: "2024-01-07T12:15:00.000Z",
    urgent: false,
    featured: true
  },
  {
    _id: "10",
    title: "Data Science Mentor",
    category: "teaching",
    type: "Contract",
    location: "Remote",
    experience: "3-4 years",
    salary: "₹6-8 LPA",
    description: "Guide students through data science projects, teach Python libraries (Pandas, NumPy, Scikit-learn), and help with machine learning concepts and projects.",
    posted: "2024-01-06T14:45:00.000Z",
    urgent: false,
    featured: false
  }
];